"""add cardmarket ids

Revision ID: 4928e3e09350
Revises: 6854c91e7389
Create Date: 2026-06-22 19:38:09.993640

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "4928e3e09350"
down_revision: str | Sequence[str] | None = "6854c91e7389"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("card_sets", sa.Column("cardmarket_expansion_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_card_sets_cardmarket_expansion_id"),
        "card_sets",
        ["cardmarket_expansion_id"],
        unique=False,
    )
    op.add_column("cards", sa.Column("cardmarket_product_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_cards_cardmarket_product_id"), "cards", ["cardmarket_product_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cards_cardmarket_product_id"), table_name="cards")
    op.drop_column("cards", "cardmarket_product_id")
    op.drop_index(op.f("ix_card_sets_cardmarket_expansion_id"), table_name="card_sets")
    op.drop_column("card_sets", "cardmarket_expansion_id")
    # ### end Alembic commands ###
