"""add_printed_total_to_card_sets

Revision ID: 6854c91e7389
Revises: c190957c81df
Create Date: 2026-06-21 18:16:11.701567

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6854c91e7389'
down_revision: str | Sequence[str] | None = 'c190957c81df'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_sets', sa.Column('printed_total', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card_sets', 'printed_total')
    # ### end Alembic commands ###
