"""init

Revision ID: c190957c81df
Revises:
Create Date: 2026-06-21 13:16:55.824138

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "c190957c81df"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "games",
        sa.Column("slug", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_games")),
        sa.UniqueConstraint("slug", name=op.f("uq_games_slug")),
    )
    op.create_table(
        "card_sets",
        sa.Column("game_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("language", sa.String(length=2), nullable=False),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("total_cards", sa.Integer(), nullable=True),
        sa.Column("symbol_asset_url", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["game_id"], ["games.id"], name=op.f("fk_card_sets_game_id_games"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_card_sets")),
        sa.UniqueConstraint("game_id", "code", "language", name="uq_card_sets_game_code_lang"),
    )
    op.create_index("ix_card_sets_release", "card_sets", ["release_date"], unique=False)
    op.create_table(
        "cards",
        sa.Column("game_id", sa.UUID(), nullable=False),
        sa.Column("set_id", sa.UUID(), nullable=False),
        sa.Column("number", sa.String(length=16), nullable=False),
        sa.Column("name_localized", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rarity", sa.String(length=64), nullable=True),
        sa.Column("card_type", sa.String(length=64), nullable=True),
        sa.Column("artwork_hash", sa.String(length=32), nullable=True),
        sa.Column("image_url_small", sa.Text(), nullable=True),
        sa.Column("image_url_large", sa.Text(), nullable=True),
        sa.Column("external_id", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["game_id"], ["games.id"], name=op.f("fk_cards_game_id_games"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["set_id"], ["card_sets.id"], name=op.f("fk_cards_set_id_card_sets"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cards")),
        sa.UniqueConstraint("set_id", "number", name="uq_cards_set_number"),
    )
    op.create_index("ix_cards_artwork_hash", "cards", ["artwork_hash"], unique=False)
    op.create_index(op.f("ix_cards_external_id"), "cards", ["external_id"], unique=False)
    op.create_index(
        "ix_cards_name_trgm", "cards", ["name_localized"], unique=False, postgresql_using="gin"
    )
    op.create_table(
        "card_embeddings",
        sa.Column("card_id", sa.UUID(), nullable=False),
        sa.Column("model_version", sa.String(length=32), nullable=False),
        sa.Column("vector", pgvector.sqlalchemy.Vector(dim=384), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["cards.id"],
            name=op.f("fk_card_embeddings_card_id_cards"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_card_embeddings")),
        sa.UniqueConstraint("card_id", name=op.f("uq_card_embeddings_card_id")),
    )
    op.create_table(
        "card_variants",
        sa.Column("card_id", sa.UUID(), nullable=False),
        sa.Column("language", sa.String(length=2), nullable=False),
        sa.Column("edition", sa.String(length=32), nullable=False),
        sa.Column("finish", sa.String(length=32), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["cards.id"],
            name=op.f("fk_card_variants_card_id_cards"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_card_variants")),
        sa.UniqueConstraint(
            "card_id", "language", "edition", "finish", name="uq_card_variants_identity"
        ),
    )
    op.create_table(
        "scans",
        sa.Column("matched_card_id", sa.UUID(), nullable=True),
        sa.Column("similarity", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("client_version", sa.String(length=32), nullable=True),
        sa.Column("model_version", sa.String(length=32), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["matched_card_id"],
            ["cards.id"],
            name=op.f("fk_scans_matched_card_id_cards"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scans")),
    )
    op.create_table(
        "prices",
        sa.Column("variant_id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("condition", sa.String(length=8), nullable=False),
        sa.Column("price_eur", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("trend_7d_eur", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["card_variants.id"],
            name=op.f("fk_prices_variant_id_card_variants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prices")),
    )
    op.create_index("ix_prices_source", "prices", ["source"], unique=False)
    op.create_index(
        "ix_prices_variant_fetched", "prices", ["variant_id", "fetched_at"], unique=False
    )

    # HNSW-Index fuer pgvector (manuell, da Alembic HNSW noch nicht reflektiert).
    op.execute(
        "CREATE INDEX ix_card_embeddings_vector_hnsw "
        "ON card_embeddings USING hnsw (vector vector_cosine_ops) "
        "WITH (m = 16, ef_construction = 64)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_card_embeddings_vector_hnsw")
    op.drop_index("ix_prices_variant_fetched", table_name="prices")
    op.drop_index("ix_prices_source", table_name="prices")
    op.drop_table("prices")
    op.drop_table("scans")
    op.drop_table("card_variants")
    op.drop_table("card_embeddings")
    op.drop_index("ix_cards_name_trgm", table_name="cards", postgresql_using="gin")
    op.drop_index(op.f("ix_cards_external_id"), table_name="cards")
    op.drop_index("ix_cards_artwork_hash", table_name="cards")
    op.drop_table("cards")
    op.drop_index("ix_card_sets_release", table_name="card_sets")
    op.drop_table("card_sets")
    op.drop_table("games")
    # ### end Alembic commands ###
